version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always   # También hay un error tipográfico aquí, debería ser "always" en lugar de "alwais"
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
